// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyzxehjitzaiithwrnbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5enhlaGppdHphaWl0aHdybmJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4OTU2NjIsImV4cCI6MjA2NzQ3MTY2Mn0.4j9sy9E-9WFjuapZgF1lsrSeXgWka9NmIRMnDw4--oQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});